Repository 21130449-NguyenKhaiNam/web-sell, pull requests merged in 2024-06, with the labels that each got.

#66 hoàn thành xuất file
  pom.xml
  src/main/java/controller/web/admin/log/ExportExcelLog.java
  src/main/java/controller/web/admin/order/ExportExcelOrder.java
  src/main/java/controller/web/admin/product/ExportExcelProduct.java
  src/main/java/controller/web/admin/user/ExportExcelUser.java
  src/main/java/controller/web/review/ExportExcelReview.java
  src/main/java/dao/GeneralDao.java
  src/main/java/dao/ILogDAO.java
  src/main/java/dao/LogDAOImp.java
  src/main/java/dao/OrderDetailDAO.java
  src/main/java/dao/ProductCardDAO.java
  src/main/java/dao/ReviewDAO.java
  src/main/java/database/JDBIConnector.java
  src/main/java/services/LogService.java
  src/main/java/services/admin/AdminProductServices.java
  src/main/java/services/admin/AdminReviewServices.java
  src/main/webapp/assets/css/admin/admin.css
  src/main/webapp/assets/css/admin/adminProducts.css
  src/main/webapp/js/admin/adminProducts.js
  src/main/webapp/public/admin/adminOrders.jsp
  src/main/webapp/public/admin/adminProducts.jsp
  src/main/webapp/public/admin/adminReviews.jsp
  src/main/webapp/public/admin/adminUsers.jsp
  src/test/java/CloundinaryTest.java
Labels: enhancement

#67 sửa lỗi tràn heap
  src/main/java/controller/web/admin/log/ExportExcelLog.java
  src/main/java/controller/web/admin/order/ExportExcelOrder.java
  src/main/java/controller/web/admin/product/ExportExcelProduct.java
  src/main/java/controller/web/admin/user/ExportExcelUser.java
  src/main/java/dao/GeneralDao.java
  src/main/java/dao/ILogDAO.java
  src/main/java/dao/LogDAOImp.java
  src/main/java/dao/OrderDaoAdmin.java
  src/main/java/dao/ProductCardDAO.java
  src/main/java/dao/ProductDao.java
  src/main/java/dao/UserDAO.java
  src/main/java/models/Log.java
  src/main/java/services/LogService.java
  src/main/java/services/UserServices.java
  src/main/java/services/admin/AdminOrderServices.java
  src/main/java/services/admin/AdminProductServices.java
  src/main/webapp/assets/css/admin/admin.css
  src/main/webapp/public/admin/adminLogs.jsp
  src/test/java/CloundinaryTest.java
Labels: bug

#69 Fix Admin Navigate Navbar
  src/main/java/controller/api/checkout/CheckoutController.java
  src/main/java/controller/web/admin/log/ExportExcelLog.java
  src/main/java/dao/GeneralDao.java
  src/main/java/dao/ILogDAO.java
  src/main/java/dao/LogDAOImp.java
  src/main/java/dao/ShoppingCartDao.java
  src/main/java/filter/adminPage/AdminOrders.java
  src/main/java/filter/authorization/ModRole.java
  src/main/java/services/LogService.java
  src/main/webapp/assets/css/modal.css
  src/main/webapp/js/admin/adminOrders.js
  src/main/webapp/js/admin/adminVoucher.js
  src/main/webapp/js/modal.js
  src/main/webapp/public/about.jsp
  src/main/webapp/public/admin/adminCategories.jsp
  src/main/webapp/public/admin/adminLink.jsp
  src/main/webapp/public/admin/adminLogs.jsp
  src/main/webapp/public/admin/adminNavigator.jsp
  src/main/webapp/public/admin/adminOrders.jsp
  src/main/webapp/public/admin/adminProducts.jsp
  src/main/webapp/public/admin/adminReviews.jsp
  src/main/webapp/public/admin/adminUsers.jsp
  src/main/webapp/public/admin/adminVoucher.jsp
  src/main/webapp/public/commonLink.jsp
  src/main/webapp/public/contact.jsp
  src/main/webapp/public/header.jsp
  src/main/webapp/public/index.jsp
  src/main/webapp/public/modal.jsp
  src/main/webapp/public/product/productBuying.jsp
  src/main/webapp/public/user/shoppingCart.jsp
Labels: bug

#72 Admin User và admin Voucher
  src/main/java/controller/api/admin/user/CreateUserController.java
  src/main/java/controller/api/admin/user/UpdateUserController.java
  src/main/java/controller/api/admin/user/UserControllerAPI.java
  src/main/java/controller/api/admin/user/UserDatatableController.java
  src/main/java/controller/api/admin/voucher/UpdateVoucherController.java
  src/main/java/controller/web/admin/user/AddUser.java
  src/main/java/controller/web/admin/user/LoadDataUser.java
  src/main/java/controller/web/admin/user/UpdateUser.java
  src/main/java/controller/web/authentication/SignUp.java
  src/main/java/dao/GeneralDao.java
  src/main/java/dao/UserDAO.java
  src/main/java/dao/VoucherDAO.java
  src/main/java/models/User.java
  src/main/java/services/UserServices.java
  src/main/java/services/authentication/AuthenticateServices.java
  src/main/java/services/voucher/VoucherServices.java
  src/main/java/utils/Comparison.java
  src/main/webapp/assets/css/admin/adminUsers.css
  src/main/webapp/assets/css/logIn.css
  src/main/webapp/js/admin/adminUsers.js
  src/main/webapp/js/admin/adminVoucher.js
  src/main/webapp/js/base.js
  src/main/webapp/js/user/accountInfo.js
  src/main/webapp/public/admin/adminLink.jsp
  src/main/webapp/public/admin/adminUsers.jsp
  src/main/webapp/public/admin/adminVoucher.jsp
  src/main/webapp/public/auth/signUp.jsp
  src/main/webapp/public/commonLink.jsp
Labels: bug, enhancement

#81 Create LICENSE
  LICENSE
Labels: documentation

#80 Sửa lỗi tại các trang: Đăng nhập, Đăng ký, Quên mật khẩu, Điều chỉnh thông tin cá nhân
  src/main/java/controller/api/user/UpdateInfoController.java
  src/main/java/controller/api/user/UploadAvatarController.java
  src/main/java/controller/web/account/UploadAvatar.java
  src/main/java/controller/web/authentication/SignIn.java
  src/main/java/controller/web/authentication/SignUp.java
  src/main/java/dao/UserDAO.java
  src/main/java/filter/home/Home.java
  src/main/java/filter/recaptcha/ReCaptchaFilter.java
  src/main/java/filter/user/AccountFilter.java
  src/main/java/services/BackupService.java
  src/main/java/services/authentication/AuthenticateServices.java
  src/main/java/session/SessionManager.java
  src/main/webapp/assets/css/base.css
  src/main/webapp/assets/css/user/accountInfo.css
  src/main/webapp/js/user/accountInfo.js
  src/main/webapp/js/validateForm.js
  src/main/webapp/public/auth/forgotPassword.jsp
  src/main/webapp/public/auth/signIn.jsp
  src/main/webapp/public/auth/signUp.jsp
  src/main/webapp/public/header.jsp
  src/main/webapp/public/index.jsp
  src/main/webapp/public/user/accountInfo.jsp
  src/main/webapp/public/user/accountNavigator.jsp
Labels: bug
